In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import random
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
from sklearn import preprocessing
from keras.preprocessing.text import Tokenizer
from keras import models
from keras import layers
from keras import optimizers

Using Theano backend.


### Load the Data
The objective is to build a neural network using Keras. Create a classification model using Deep Learning.  I will be using the Keras library.  Evaluate performance of a neural network using Keras.

In [15]:
data = pd.read_csv('data/complaints.csv', error_bad_lines=False, engine="python")

In [16]:
data.head(50)

Product                       Consumer complaint narrative
0   Student loan  In XX/XX/XXXX I filled out the Fedlaon applica...
1   Student loan  I am being contacted by a debt collector for p...
2   Student loan  I cosigned XXXX student loans at SallieMae for...
3   Student loan  Navient has sytematically and illegally failed...
4   Student loan  My wife became eligible for XXXX Loan Forgiven...
5   Student loan  Hello, I am a XXXX resident who has multiple X...
6   Student loan  My account was sold to them and expect me to p...
7   Student loan  On XX/XX/XXXX, I was sued in XXXX County, XXXX...
8   Student loan  To Whom It May Concern, I applied for a privat...
9   Student loan  My loans through XXXX were deferred as I am a ...
10  Student loan  National Collegiate and trust has been on my C...
11  Student loan  Just received information about the lawsuit fi...
12  Student loan  Calls are being made to all different numbers ...
13  Student loan  My loans are in the process of being transferr...
14  Student loan  I have a $ XXXX+ loan with AES and have tried ...
15  Student loan  I was told that the Fed Loan Help company was ...
16  Student loan  My private loans are serviced through AES. I l...
17  Student loan  I have had SEVERAL issues with XXXX XXXX/Navie...
18  Student loan  XX/XX/XXXX, I graduated from XXXX. Unknown to ...
19  Student loan  I have already filed several complaints about ...
20  Student loan  I feel as if my student loans through Navient ...
21  Student loan  I have XXXX variable interest rate loans throu...
22  Student loan  I have student loans totaling slightly over {$...
23  Student loan  I tried to consolidate my loan into my home lo...
24  Student loan  Was constantly told I had to pay a high monthl...
25  Student loan  I refinanced my loan from Navient XX/XX/XXXX. ...
26  Student loan  ACS has been applying my entire monthly paymen...
27  Student loan  Enclosed is all the information that is attatc...
28  Student loan  Navient is committing the same offenses they c...
29  Student loan  I had a student loan from XX/XX/XXXX.for {$250...
30  Student loan  I contacted XXXX out of XXXX because I heard t...
31  Student loan  On XX/XX/XXXX I was told by XXXX from Navient ...
32  Student loan  I was shocked when I reviewed my credit report...
33  Student loan  In XXXX 2016 I renewed my rate reduction progr...
34  Student loan  In  2005 a student loan application was proces...
35  Student loan  Since I graduated college in  XXXX  I have pai...
36  Student loan  Recently I was informed that I have a loan wit...
37  Student loan  Every time I make a principal only payment, th...
38  Student loan  XXXX XXXX XXXX reached out to me on XXXX XXXX,...
39  Student loan  FedLoan Servicing will not allow borrowers to ...
40  Student loan  I have Federal and Private Student Loans I rep...
41  Student loan  I paid off my loan with sallie mae years ago a...
42  Student loan  I was forced to sign documents I did n't under...
43  Student loan  I contacted FedLoans Servicing this morning to...
44  Student loan  I have requested to release my cosigner for th...
45  Student loan  I have student loans that I 'm repaying to XXX...
46  Student loan  I graduated college in XX/XX/XXXX. I had a pri...
47  Student loan  I have my loans with XXXX. There have been mul...
48  Student loan  I am have been making payments to Navient priv...
49  Student loan  I graduated from XXXX XXXX XXXX XXXX, 2015. Th...

In [17]:
data.shape

(23795, 2)

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23795 entries, 0 to 23794
Data columns (total 2 columns):
 #   Column                        Non-Null Count  Dtype 
---  ------                        --------------  ----- 
 0   Product                       23795 non-null  object
 1   Consumer complaint narrative  23795 non-null  object
dtypes: object(2)
memory usage: 371.9+ KB


data.isna().sum()

In [20]:
data['Product'].value_counts()

Student loan               11404
Credit card                 9540
Bank account or service     2851
Name: Product, dtype: int64

### Preprocessing
Before we build our neural network, we need to do several preprocessing steps. First, we will create word vector counts (a bag of words type representation) of our complaints text. Next, we will change 
the category labels to integers. Finally, we will perform our usual train-test split before building and training our neural network using Keras. 

### One-hot encoding of the complaints
Our first step again is to transform our textual data into a numerical representation. As we saw in some of our previous lessons on NLP, there are many ways to do this. Here, we'll use the Tokenizer() class from the preprocessing.text sub-module of the Keras package.

As with our previous work using NLTK, this will transform our text complaints into word vectors. (Note that the method of creating a vector is different from our previous work with NLTK; as you'll see, word order will be preserved as opposed to a bag of words representation). In the below code, we'll only keep the 2,000 most common words and use one-hot encoding.

In [23]:
# Raw text complaints
complaints = data['Consumer complaint narrative'] 

# Initialize a tokenizer 
tokenizer = Tokenizer(num_words=2000) 

# Fit it to the complaints
tokenizer.fit_on_texts(complaints) 

# Generate sequences
sequences = tokenizer.texts_to_sequences(complaints) 
print('sequences type:', type(sequences))

# Similar to sequences, but returns a numpy array
one_hot_results= tokenizer.texts_to_matrix(complaints, mode='binary') 
print('one_hot_results type:', type(one_hot_results))

# Useful if we wish to decode (more explanation below)
word_index = tokenizer.word_index 

# Tokens are the number of unique words across the corpus
print('Found %s unique tokens.' % len(word_index)) 

# Our coded data
print('Dimensions of our coded results:', np.shape(one_hot_results)) 

sequences type: <class 'list'>
one_hot_results type: <class 'numpy.ndarray'>
Found 28752 unique tokens.
Dimensions of our coded results: (23795, 2000)


In [25]:
reverse_index = dict([(value, key) for (key, value) in word_index.items()])
reverse_index

{1: 'i',
 2: 'the',
 3: 'xxxx',
 4: 'to',
 5: 'and',
 6: 'my',
 7: 'a',
 8: 'that',
 9: 'of',
 10: 'was',
 11: 'in',
 12: 'they',
 13: 'for',
 14: 'on',
 15: 'have',
 16: 'not',
 17: 'me',
 18: 'this',
 19: 'is',
 20: 'with',
 21: 'it',
 22: 'xx',
 23: 'account',
 24: 'credit',
 25: '00',
 26: 'had',
 27: 'loan',
 28: 'from',
 29: 'payment',
 30: 'be',
 31: 'as',
 32: 'would',
 33: 'card',
 34: 'them',
 35: 'been',
 36: 'at',
 37: 'but',
 38: 'loans',
 39: 'payments',
 40: 'an',
 41: 'told',
 42: 'no',
 43: 'bank',
 44: 'by',
 45: 'or',
 46: 'when',
 47: 'did',
 48: 'are',
 49: 'am',
 50: 'do',
 51: "n't",
 52: 'pay',
 53: 'interest',
 54: 'time',
 55: 'has',
 56: 'which',
 57: 'were',
 58: 'so',
 59: 'all',
 60: 'their',
 61: 'called',
 62: 'navient',
 63: 'because',
 64: 'if',
 65: 'out',
 66: 'after',
 67: 'received',
 68: 'we',
 69: 'can',
 70: "''",
 71: 'any',
 72: 'you',
 73: 'could',
 74: "'s",
 75: 'due',
 76: 'never',
 77: 'student',
 78: 'up',
 79: 'about',
 80: 'will',
 81:

In [28]:
comment_idx_to_preview = 19
print('Original complaint text:')
print(complaints[comment_idx_to_preview])
print('\n\n')

#The reverse_index cell block above must be complete in order for this cell block to successively execute.
decoded_review = ' '.join([reverse_index.get(i) for i in sequences[comment_idx_to_preview]])
print('Decoded review from Tokenizer:')
print(decoded_review)

Original complaint text:
I have already filed several complaints about AES/PHEAA. I was notified by a XXXX XXXX let @ XXXX, who pretended to be from your office, he said he was from CFPB. I found out this morning he is n't from your office, but is actually works at XXXX. 

This has wasted weeks of my time. They AES/PHEAA confirmed and admitted ( see attached transcript of XXXX, conversation at XXXX ( XXXX ) with XXXX that proves they verified the loans are not mine ) the student loans they had XXXX, and collected on, and reported negate credit reporting in my name are in fact, not mine. 
They conclued their investigation on XXXX admitting they made a mistake and have my name on soneone elses loans. I these XXXX loans total {$10000.00}, original amount. My XXXX loans I got was total {$3500.00}. We proved by providing AES/PHEAA, this with my original promissary notes I located recently, the XXXX of my college provided AES/PHEAA with their original shoeinf amounts of my XXXX loans which s

In [31]:
### Convert the Products to Numerical Categories

In [30]:
product = data['Product']

# Initialize
le = preprocessing.LabelEncoder() 
le.fit(product)
print('Original class labels:')
print(list(le.classes_))
print('\n')
product_cat = le.transform(product)  

# If you wish to retrieve the original descriptive labels post production
# list(le.inverse_transform([0, 1, 3, 3, 0, 6, 4])) 

print('New product labels:')
print(product_cat)
print('\n')

# Each row will be all zeros except for the category for that observation 
print('One hot labels; 7 binary columns, one for each of the categories.') 
product_onehot = to_categorical(product_cat)
print(product_onehot)
print('\n')

print('One hot labels shape:')
print(np.shape(product_onehot))

Original class labels:
['Bank account or service', 'Credit card', 'Student loan']


New product labels:
[2 2 2 ... 0 0 0]


One hot labels; 7 binary columns, one for each of the categories.
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


One hot labels shape:
(23795, 3)


In [37]:
product_onehot.shape

(23795, 3)

In [38]:
product_onehot

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

### Train-test split

In [32]:
from sklearn.model_selection import train_test_split 

In [35]:
product_cat

array([2, 2, 2, ..., 0, 0, 0])

In [ ]:
X = data['']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)